import { Node, Edge } from "@xyflow/react";

// 定义节点数据
export const initialNodes: Node[] = [
    //制片段
    {
        id: "0",
        type: "group",
        data: { label: "制片段" },
        position: { x: 0, y: 0 },
        style: {
            width: 1800,
            height: 500,
            backgroundColor: "rgba(240, 240, 240, 0.1)",
            border: "1px dashed #ccc",
            borderRadius: 8,
        },
        draggable: false,
    },
    {
        id: "C021",
        type: "Node_Start",
        data: { label: "正极搅拌", url: "/正极搅拌", process: "C021" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "C022",
        type: "Node_Start",
        data: { label: "陶瓷搅拌", url: "/陶瓷搅拌", process: "C022" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "C023",
        type: "Node_Start",
        data: { label: "底涂搅拌", url: "/底涂搅拌", process: "C023" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "C030",
        type: "Node_Left_with_Right",
        data: { label: "正极涂布", url: "/正极涂布", process: "C030" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "C040",
        type: "Node_Left_with_Right",
        data: { label: "正极辊分", url: "/正极辊分", process: "C040" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "A020",
        type: "Node_Start",
        data: { label: "负极搅拌", url: "/负极搅拌", process: "A020" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "A030",
        type: "Node_Left_with_Right",
        data: { label: "负极涂布", url: "/负极涂布", process: "A030" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "A040",
        type: "Node_Left_with_Right",
        data: { label: "负极辊分", url: "/负极辊分", process: "A040" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
        extent: "parent",
    },
    {
        id: "A050",
        type: "Node_LEnd",
        data: { label: "极片库", url: "/", process: "A050" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "0",
    },
    {
        id: "1",
        type: "group",
        data: { label: "切叠段" },
        position: { x: 0, y: 500 },
        style: {
            width: 1800,
            height: 150,
            backgroundColor: "rgba(240, 240, 240, 0.1)",
            border: "1px dashed #ccc",
            borderRadius: 8,
        },
        draggable: false,
    },
    {
        id: "S010",
        type: "Node_None",
        data: { label: "切叠热压", url: "/切叠热压", process: "S010" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "1",
        extent: "parent",
    },
    // 组装段
    {
        id: "2",
        type: "group",
        data: { label: "组装段" },
        position: { x: 0, y: 650 },
        style: {
            width: 1800,
            height: 250,
            backgroundColor: "rgba(240, 240, 240, 0.1)",
            border: "1px dashed #ccc",
            borderRadius: 8,
        },
        draggable: false,
    },
    {
        id: "E010",
        type: "Node_Start",
        data: { label: "X-Ray01", url: "/X-Ray01", process: "E010" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E020",
        type: "Node_Left_with_Right",
        data: { label: "极耳预焊", url: "/极耳预焊", process: "E020" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E030",
        type: "Node_Left_with_Right",
        data: { label: "极耳终焊", url: "/极耳终焊", process: "E030" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E040",
        type: "Node_Left_with_Right",
        data: { label: "盖板&连接片焊接前", url: "/盖板&连接片焊接前", process: "E040" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E050",
        type: "Node_Left_with_Right",
        data: { label: "包PET膜", url: "/包PET膜", process: "E050" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E060",
        type: "Node_Left_with_Right",
        data: { label: "入壳预焊", url: "/入壳预焊", process: "E060" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E070",
        type: "Node_Left_with_Right",
        data: { label: "盖板满焊", url: "/盖板满焊", process: "E070" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E080",
        type: "Node_Left_with_Bottom",
        data: { label: "X-Ray02", url: "/X-Ray02", process: "E080" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E090",
        type: "Node_Top_with_Left",
        data: { label: "前氦检", url: "/前氦检", process: "E090" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "E100",
        type: "Node_REnd",
        data: { label: "真空烘烤", url: "/真空烘烤", process: "E100" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "2",
        extent: "parent",
    },
    {
        id: "3",
        type: "group",
        data: { label: "化成段" },
        position: { x: 0, y: 900 },
        style: {
            width: 1800,
            height: 450,
            backgroundColor: "rgba(240, 240, 240, 0.1)",
            border: "1px dashed #ccc",
            borderRadius: 8,
        },
        draggable: false,
    },
    {
        id: "E110",
        type: "Node_Start",
        data: { label: "一次注液", url: "/一次注液", process: "E110" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F010",
        type: "Node_Left_with_Right",
        data: { label: "高温静置", url: "/高温静置", process: "F010" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F020",
        type: "Node_Left_with_Right",
        data: { label: "OCV01", url: "/OCV01", process: "F020" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F030",
        type: "Node_Left_with_Right",
        data: { label: "拔化成钉", url: "/  拔化成钉", process: "F030" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F040",
        type: "Node_Left_with_Right",
        data: { label: "化成", url: "/化成", process: "F040" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F050",
        type: "Node_Left_with_Right",
        data: { label: "入化成钉", url: "/入化成钉", process: "F050" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F060",
        type: "Node_Left_with_Right",
        data: { label: "高温静置2", url: "/高温静置2", process: "F060" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F070",
        type: "Node_Left_with_Bottom",
        data: { label: "OCV1", url: "/OCV1", process: "F070" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F080",
        type: "Node_Top_with_Left",
        data: { label: "二次注液", url: "/二次注液", process: "F080" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F090",
        type: "Node_Right_with_Left",
        data: { label: "密封钉焊接", url: "/密封钉焊接", process: "F090" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F100",
        type: "Node_Right_with_Left",
        data: { label: "后氦检", url: "/后氦检", process: "F100" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F110",
        type: "Node_Right_with_Left",
        data: { label: "加拘束1", url: "/加拘束1", process: "F110" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F120",
        type: "Node_Right_with_Left",
        data: { label: "SOC调整", url: "/SOC调整", process: "F120" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F130",
        type: "Node_Right_with_Left",
        data: { label: "高温静置3", url: "/高温静置3", process: "F130" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F140",
        type: "Node_Right_with_Left",
        data: { label: "常温静置", url: "/常温静置", process: "F140" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F150",
        type: "Node_Right_with_Bottom",
        data: { label: "OCV2", url: "/OCV2", process: "F150" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F160",
        type: "Node_Top_with_Right",
        data: { label: "常温静置2", url: "/常温静置2", process: "F160" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F170",
        type: "Node_Left_with_Right",
        data: { label: "OCV3", url: "/OCV3", process: "F170" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F180",
        type: "Node_Left_with_Right",
        data: { label: "加拘束2", url: "/加拘束2", process: "F180" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F190",
        type: "Node_Left_with_Right",
        data: { label: "分容", url: "/分容", process: "F190" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F200",
        type: "Node_Left_with_Right",
        data: { label: "常温静置3", url: "/常温静置3", process: "F200" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F210",
        type: "Node_Left_with_Right",
        data: { label: "OCV4", url: "/OCV4", process: "F210" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F220",
        type: "Node_Left_with_Right",
        data: { label: "常温静置4", url: "/常温静置4", process: "F220" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F230",
        type: "Node_Left_with_Bottom",
        data: { label: "OCV5", url: "/OCV5", process: "F230" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F240",
        type: "Node_Top_with_Left",
        data: { label: "常温静置5", url: "/常温静置5", process: "F240" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F250",
        type: "Node_Right_with_Left",
        data: { label: "OCV6", url: "/OCV6", process: "F250" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F260",
        type: "Node_Right_with_Left",
        data: { label: "DCIR", url: "/DCIR", process: "F260" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "F270",
        type: "Node_REnd",
        data: { label: "常温静置6", url: "/常温静置6", process: "F270" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "3",
        extent: "parent",
    },
    {
        id: "4",
        type: "group",
        data: { label: "包装段" },
        position: { x: 0, y: 1350 },
        style: {
            width: 1800,
            height: 150,
            backgroundColor: "rgba(240, 240, 240, 0.1)",
            border: "1px dashed #ccc",
            borderRadius: 8,
        },
        draggable: false,
    },
    {
        id: "P010",
        type: "Node_Start",
        data: { label: "焊缝辊压检测", url: "/焊缝辊压检测", process: "P010" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
    {
        id: "P020",
        type: "Node_Left_with_Right",
        data: { label: "电芯清洗1", url: "/电芯清洗1", process: "P020" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
    {
        id: "P030",
        type: "Node_Left_with_Right",
        data: { label: "电芯清洗2", url: "/电芯清洗2", process: "P030" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
    {
        id: "P040",
        type: "Node_Left_with_Right",
        data: { label: "UV喷涂A", url: "/UV喷涂A", process: "P040" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
    {
        id: "P050",
        type: "Node_Left_with_Right",
        data: { label: "UV喷涂B", url: "/UV喷涂B", process: "P050" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
    {
        id: "P060",
        type: "Node_LEnd",
        data: { label: "外观检测", url: "/外观检测", process: "P060" },
        position: { x: 0, y: 0 },
        draggable: false,
        parentId: "4",
        extent: "parent",
    },
];

// 定义边数据
export const initialEdges: Edge[] = [
    // 制片段连接
    {
        id: "c021-c030",
        source: "C021",
        target: "C030",
        animated: false,
    },
    {
        id: "c023-c030",
        source: "C023",
        target: "C030",
        animated: false,
    },
    {
        id: "c022-c030",
        source: "C022",
        target: "C030",
        animated: false,
    },
    {
        id: "c030-c040",
        source: "C030",
        target: "C040",
        animated: false,
    },
    {
        id: "a020-a030",
        source: "A020",
        target: "A030",
        animated: false,
    },
    {
        id: "a030-a040",
        source: "A030",
        target: "A040",
        animated: false,
    },
    {
        id: "c040-a050",
        source: "C040",
        target: "A050",
        animated: false,
    },
    {
        id: "a040-a050",
        source: "A040",
        target: "A050",
        animated: false,
    },
    // 组装段连接
    {
        id: "e010-e020",
        source: "E010",
        target: "E020",
        animated: false,
    },
    {
        id: "e020-e030",
        source: "E020",
        target: "E030",
        animated: false,
    },
    {
        id: "e030-e040",
        source: "E030",
        target: "E040",
        animated: false,
    },
    {
        id: "e040-e050",
        source: "E040",
        target: "E050",
        animated: false,
    },
    {
        id: "e050-e060",
        source: "E050",
        target: "E060",
        animated: false,
    },
    {
        id: "e060-e070",
        source: "E060",
        target: "E070",
        animated: false,
    },
    {
        id: "e070-e080",
        source: "E070",
        target: "E080",
        animated: false,
    },
    {
        id: "e080-e090",
        source: "E080",
        target: "E090",
        animated: false,
    },
    {
        id: "e090-e100",
        source: "E090",
        target: "E100",
        animated: false,
    },
    // 化成段连接
    {
        id: "e110-f010",
        source: "E110",
        target: "F010",
        animated: false,
    },
    {
        id: "f010-f020",
        source: "F010",
        target: "F020",
        animated: false,
    },
    {
        id: "f020-f030",
        source: "F020",
        target: "F030",
        animated: false,
    },
    {
        id: "f030-f040",
        source: "F030",
        target: "F040",
        animated: false,
    },
    {
        id: "f040-f050",
        source: "F040",
        target: "F050",
        animated: false,
    },
    {
        id: "f050-f060",
        source: "F050",
        target: "F060",
        animated: false,
    },
    {
        id: "f060-f070",
        source: "F060",
        target: "F070",
        animated: false,
    },
    {
        id: "f070-f080",
        source: "F070",
        target: "F080",
        animated: false,
    },
    {
        id: "f080-f090",
        source: "F080",
        target: "F090",
        animated: false,
    },
    {
        id: "f090-f100",
        source: "F090",
        target: "F100",
        animated: false,
    },
    {
        id: "f100-f110",
        source: "F100",
        target: "F110",
        animated: false,
    },
    {
        id: "f110-f120",
        source: "F110",
        target: "F120",
        animated: false,
    },
    {
        id: "f120-f130",
        source: "F120",
        target: "F130",
        animated: false,
    },
    {
        id: "f130-f140",
        source: "F130",
        target: "F140",
        animated: false,
    },
    {
        id: "f140-f150",
        source: "F140",
        target: "F150",
        animated: false,
    },
    {
        id: "f150-f160",
        source: "F150",
        target: "F160",
        animated: false,
    },
    {
        id: "f160-f170",
        source: "F160",
        target: "F170",
        animated: false,
    },
    {
        id: "f170-f180",
        source: "F170",
        target: "F180",
        animated: false,
    },
    {
        id: "f180-f190",
        source: "F180",
        target: "F190",
        animated: false,
    },
    {
        id: "f190-f200",
        source: "F190",
        target: "F200",
        animated: false,
    },
    {
        id: "f200-f210",
        source: "F200",
        target: "F210",
        animated: false,
    },
    {
        id: "f210-f220",
        source: "F210",
        target: "F220",
        animated: false,
    },
    {
        id: "f220-f230",
        source: "F220",
        target: "F230",
        animated: false,
    },
    {
        id: "f230-f240",
        source: "F230",
        target: "F240",
        animated: false,
    },
    {
        id: "f240-f250",
        source: "F240",
        target: "F250",
        animated: false,
    },
    {
        id: "f250-f260",
        source: "F250",
        target: "F260",
        animated: false,
    },
    {
        id: "f260-f270",
        source: "F260",
        target: "F270",
        animated: false,
    },
    // 包装段连接
    {
        id: "p010-p020",
        source: "P010",
        target: "P020",
        animated: false,
    },
    {
        id: "p020-p030",
        source: "P020",
        target: "P030",
        animated: false,
    },
    {
        id: "p030-p040",
        source: "P030",
        target: "P040",
        animated: false,
    },
    {
        id: "p040-p050",
        source: "P040",
        target: "P050",
        animated: false,
    },
    {
        id: "p050-p060",
        source: "P050",
        target: "P060",
        animated: false,
    },
];
